# Generated by Django 4.2.5 on 2023-11-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
